name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          output_file: "./workflow-diagram.svg"
          excluded_paths: ".github"
          artifact_name: "havamal-diagram"
      - name: Get artifact
        should_push: false
        uses: actions/download-artifact@v2
        with:
          name: "havamal-diagram"
          path: "downloads"